language: node_js
node_js:
- '8'
install:
- npm i -g metricly-cli
script:
- metricly package validate && metricly package lint
notifications:
  slack:
    secure: Ww+p++zYM7pY1XXxF9hVjRy5UW4ZAmAxfE6lJt4dC+dy2zud3cCOZRkft4QN0HHaRJD4QOs3OuDk1PI5+8YtP8L0mqOWUU2WLLdxCY3FuCEZBHSUqNzWG2GdPlasn+O0e6eIAudkCR1a0t3k1q2xgJF6lttFRDJLt196cwpgSwullpX/dbUEZm8AwKbERvH/647qJqNGKt8/qCB05NAxa7p9kocRqEIyOUQuZ0Ewfd85WM4NuluQu9PoRm4P7uf91eiNfN5cAzQ1c5vtiL6zr2wINhWqk+G7vARxpc3KJ7K27ZCPiEYAhpMZb+e0kAcko+sRsTvs6GrJdVF9fd3AqiV9ojITQ20TkjBHqSyaNO4q9iVGy2eiPZ3v7BGXOGC2+rWtFDZKbawdANco0xS8oDcKDQUssbt4FWINISX2wcGNp/koh69JujNMj6z2a8GZhHJXAfCYFbl2Zkj0XhpEcqqDDz9Zg5AdmpP4ofSivS9VuC3UMkJFklyoOFbdjnKSlke2jBFZ59XzAA4BxJ244ZFoLWbTyxAmtPJuzmZ4T0oxtUuaoccYFQnZRWJxkcbwiYqc7HVmPg5Dohty7R6/lmNnatsKX/MuMOCm8RYZAU2Rwcc8qZQUJgjZqphphQej83ZJUdoQFKhLtsUkvIaCbjmHWHMGU0duuQDEc+nXdcQ=
